DROP SCHEMA IF EXISTS FERIA_PLACARCITO ;
CREATE SCHEMA IF NOT EXISTS  FERIA_PLACARCITO ; 
USE FERIA_PLACARCITO ;

CREATE TABLE PRODUCTO (
ID_PRODUCTO INT AUTO_INCREMENT,
CANTIDAD INT,
ID_DNI_PROVEEDOR INT,
CATEGORIA VARCHAR (50),
SUBCATEGORIA VARCHAR (50),
ESTADO ENUM ('NUEVO', 'USADO') NOT NULL,
PRIMARY KEY (ID_PRODUCTO)
);

CREATE TABLE PROVEEDOR (
ID_PROVEEDOR INT NOT NULL AUTO_INCREMENT,
CBU VARCHAR (50),
ID_PRODUCTO INT,
ID_DNI_PROVEEDOR INT,
PRIMARY KEY (ID_PROVEEDOR)
);

CREATE TABLE CLIENTES (
ID_DNI INT,
DIRECCION VARCHAR (50),
USUARIO VARCHAR (50),
PROVINCIA VARCHAR (50),
PRIMARY KEY (ID_DNI) 
);

CREATE TABLE COBRANZAS (
ID_COBRANZAS INT NOT NULL AUTO_INCREMENT,
MONTO FLOAT,
FECHA_DE_COBRO TIMESTAMP,
MEDIO_PAGO VARCHAR (50),
ID_VENTA INT NOT NULL,
PRIMARY KEY (ID_COBRANZAS)
);

CREATE TABLE PAGOS (
ID_PAGOS INT NOT NULL AUTO_INCREMENT,
ID_COMPRA INT NOT NULL,
ID_PROVEEDOR INT NOT NULL,
MONTO FLOAT,
FECHA_DE_PAGO DATE,
MEDIO_PAGO VARCHAR (50),
PRIMARY KEY (ID_PAGOS)
);

CREATE TABLE COMPRAS (
ID_COMPRA INT NOT NULL AUTO_INCREMENT,
CANTIDAD INT,
ID_PRODUCTO INT NOT NULL,
ID_PROVEEDOR INT NOT NULL,
MONTO FLOAT,
FECHA_COMPRA DATE,
PRIMARY KEY (ID_COMPRA)
);

CREATE TABLE PRECIO_COMPRAS (
ID_PRECIO_COMPRA INT NOT NULL AUTO_INCREMENT,
PRECIO FLOAT,
FECHA_COMPRA DATE,
ID_PRODUCTO INT NOT NULL,
PRIMARY KEY (ID_PRECIO_COMPRA)
);

CREATE TABLE PRECIO_VENTA (
ID_PRECIO_VENTA INT NOT NULL AUTO_INCREMENT,
PRECIO FLOAT,
ID_PRODUCTO INT NOT NULL,
FECHA_VENTA DATE,
PRIMARY KEY (ID_PRECIO_VENTA)
);

CREATE TABLE GASTOS (
ID_GASTO INT NOT NULL AUTO_INCREMENT,
MONTO_VEP FLOAT,
MONTO_CONTADOR FLOAT,
MONTO_FACTURA_ML FLOAT,
AÑO_MES DATE,
MONTO_COMISION_ML FLOAT,
PRIMARY KEY (ID_GASTO) 
);

CREATE TABLE VENTAS (
ID_VENTA INT NOT NULL AUTO_INCREMENT,
ID_PRODUCTO INT NOT NULL,
CANTIDAD INT,
FECHA_DE_VENTA TIMESTAMP,
NUMERO_FACTURA INT,
ID_DNI INT,
PRIMARY KEY (ID_VENTA)
);

CREATE TABLE IMPUESTOS (
ID_IMPUESTO INT NOT NULL AUTO_INCREMENT,
ID_GASTO INT NOT NULL,
PROVINCIA VARCHAR (50),
MONTO FLOAT,
AÑO_MES DATE,
PRIMARY KEY (ID_IMPUESTO)
);



ALTER TABLE VENTAS
ADD FOREIGN KEY (ID_DNI) REFERENCES CLIENTES (ID_DNI),
ADD FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO);

ALTER TABLE COMPRAS
ADD FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO),
ADD FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR (ID_PROVEEDOR);

ALTER TABLE PRECIO_COMPRAS
ADD FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO);

ALTER TABLE PRECIO_VENTA
ADD FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO);

ALTER TABLE COBRANZAS
ADD FOREIGN KEY (ID_VENTA) REFERENCES VENTAS (ID_VENTA);

ALTER TABLE PAGOS
ADD FOREIGN KEY (ID_COMPRA) REFERENCES COMPRAS (ID_COMPRA);

ALTER TABLE IMPUESTOS
ADD FOREIGN KEY (ID_GASTO) REFERENCES GASTOS (ID_GASTO);

ALTER TABLE PROVEEDOR
ADD FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO);