CREATE VIEW vista_impuesto_mas_alto AS
SELECT PROVINCIA, AÑO_MES,
MAX(MONTO) AS impuesto_mas_alto
FROM IMPUESTOS
GROUP BY PROVINCIA,AÑO_MES;     

CREATE VIEW Cantidad_por_estado AS
SELECT ESTADO, COUNT(*) AS CANTIDAD
FROM PRODUCTO
GROUP BY ESTADO;

CREATE VIEW vista_productos_mas_vendidos AS
SELECT CATEGORIA, COUNT(*) AS cantidad_vendida
FROM PRODUCTO
JOIN VENTAS ON PRODUCTO.ID_PRODUCTO = VENTAS.ID_PRODUCTO
GROUP BY CATEGORIA
ORDER BY COUNT(*) DESC
LIMIT 5;