DELIMITER //
CREATE FUNCTION FN_TOTAL_GASTADO_POR_CLIENTE (ID_CLIENTE INT) RETURNS FLOAT
BEGIN 
DECLARE TOTAL_GASTADO FLOAT;
SELECT SUM(MONTO) INTO TOTAL_GASTADO
FROM COBRANZAS
WHERE ID_VENTA IN (SELECT ID_VENTA FROM VENTAS WHERE ID_DNI = ID_CLIENTE);
RETURN TOTAL_GASTADO;
END //
DELIMITER ;

DELIMITER //
CREATE FUNCTION FN_PRECIO_PROMEDIO_DE_VENTA (ANO_MES DATE) RETURNS FLOAT
BEGIN 
DECLARE PROMEDIO FLOAT; 
SELECT AVG(PRECIO) INTO PROMEDIO
FROM PRECIO_VENTA
WHERE YEAR (FECHA_VENTA) = YEAR (ANO_MES) AND MONTH (FECHA_VENTA) = MONTH (ANO_MES);
RETURN PROMEDIO;
END //
DELIMITER ;